#### Series is built on top of a Numpy array and can have named index

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a','b','c']

In [3]:
mylist = [10,20,30]

In [4]:
arr = np.array(mylist)

In [5]:
arr

array([10, 20, 30])

In [7]:
d = {'a':10,'b':20,'c':30}

In [8]:
pd.Series(data = mylist)

0    10
1    20
2    30
dtype: int64

In [11]:
pd.Series(arr) #'S' should be capitalized

0    10
1    20
2    30
dtype: int32

In [12]:
pd.Series(data=arr,index=labels)

a    10
b    20
c    30
dtype: int32

In [14]:
pd.Series(data=[10,'a',4,4]) #type can be mised

0    10
1     a
2     4
3     4
dtype: object

In [25]:
ser1 = pd.Series([1,2,3,4],index = ['USA','China','Japan','Canada'])

In [26]:
ser1

USA       1
China     2
Japan     3
Canada    4
dtype: int64

In [19]:
ser1['USA']

1

In [27]:
ser2 = pd.Series([1,4,5,6],index = ['USA','Mexico','Japan','Canada'])

In [28]:
ser2

USA       1
Mexico    4
Japan     5
Canada    6
dtype: int64

In [29]:
ser1 + ser2 #recognize same term with same index and add the together

Canada    10.0
China      NaN
Japan      8.0
Mexico     NaN
USA        2.0
dtype: float64

In [30]:
#dataframe = multiple series object with same index

In [31]:
import pandas as pd
import numpy as np

In [33]:
from numpy.random import randn
np.random.seed(101)

rand_mat = randn(5,4)

In [35]:
rand_mat

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [40]:
'A B C D E'.split()

['A', 'B', 'C', 'D', 'E']

In [44]:
df = pd.DataFrame(data = rand_mat, index = 'A B C D E'.split(), columns='W X Y Z'.split())

In [45]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [46]:
df['new'] = df['W'] + df['X']

In [47]:
df.head()

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [50]:
df.drop('new',axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [51]:
df.loc['A']

W      2.706850
X      0.628133
Y      0.907969
Z      0.503826
new    3.334983
Name: A, dtype: float64

In [56]:
df.loc[['A','E']]

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [58]:
df.loc[['A','B'],['Y','Z']]

Y         Z
A  0.907969  0.503826
B -0.848077  0.605965

In [52]:
df.iloc[2]

W     -2.018168
X      0.740122
Y      0.528813
Z     -0.589001
new   -1.278046
Name: C, dtype: float64

In [55]:
df.iloc[:,2:4]

Y         Z
A  0.907969  0.503826
B -0.848077  0.605965
C  0.528813 -0.589001
D -0.933237  0.955057
E  2.605967  0.683509

### Conditional Selection on df

In [59]:
df > 0

W      X      Y      Z    new
A   True   True   True   True   True
B   True  False  False   True   True
C  False   True   True  False  False
D   True  False  False   True  False
E   True   True   True   True   True

In [62]:
df[df > 0] #only select the values > 0

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118       NaN       NaN  0.605965  0.331800
C       NaN  0.740122  0.528813       NaN       NaN
D  0.188695       NaN       NaN  0.955057       NaN
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [63]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [65]:
df[df['W']>0] #only return the rows that satisfy this condition

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [67]:
df[df['W']>0]['Y'].loc['A'] #Stacking more conditions

0.9079694464765431

In [68]:
cond1 = df['W'] > 0
cond2 = df['Y'] > 1

In [69]:
df [cond1 and cond2] #The conditions are not designed for series

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [73]:
df[(cond1) & (cond2)] # Or df[(df['W'] > 0) & (df['Y'] > 1)]

W         X         Y         Z       new
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [74]:
df.reset_index()

index         W         X         Y         Z       new
0     A  2.706850  0.628133  0.907969  0.503826  3.334983
1     B  0.651118 -0.319318 -0.848077  0.605965  0.331800
2     C -2.018168  0.740122  0.528813 -0.589001 -1.278046
3     D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
4     E  0.190794  1.978757  2.605967  0.683509  2.169552

In [76]:
new_ind = 'CA NY WY OR CO'.split()

In [77]:
df['States'] = new_ind

In [78]:
df

W         X         Y         Z       new States
A  2.706850  0.628133  0.907969  0.503826  3.334983     CA
B  0.651118 -0.319318 -0.848077  0.605965  0.331800     NY
C -2.018168  0.740122  0.528813 -0.589001 -1.278046     WY
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177     OR
E  0.190794  1.978757  2.605967  0.683509  2.169552     CO

In [83]:
df.set_index('States', inplace=True)

In [84]:
df

W         X         Y         Z       new
States                                                  
CA      2.706850  0.628133  0.907969  0.503826  3.334983
NY      0.651118 -0.319318 -0.848077  0.605965  0.331800
WY     -2.018168  0.740122  0.528813 -0.589001 -1.278046
OR      0.188695 -0.758872 -0.933237  0.955057 -0.570177
CO      0.190794  1.978757  2.605967  0.683509  2.169552

In [86]:
df.describe()

W         X         Y         Z       new
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean   0.343858  0.453764  0.452287  0.431871  0.797622
std    1.681131  1.061385  1.454516  0.594708  1.918114
min   -2.018168 -0.758872 -0.933237 -0.589001 -1.278046
25%    0.188695 -0.319318 -0.848077  0.503826 -0.570177
50%    0.190794  0.628133  0.528813  0.605965  0.331800
75%    0.651118  0.740122  0.907969  0.683509  2.169552
max    2.706850  1.978757  2.605967  0.955057  3.334983

In [87]:
df.dtypes

W      float64
X      float64
Y      float64
Z      float64
new    float64
dtype: object

In [88]:
df['W']>0

States
CA     True
NY     True
WY    False
OR     True
CO     True
Name: W, dtype: bool

In [89]:
ser_w = df['W']>0

In [90]:
ser_w.value_counts()

True     4
False    1
Name: W, dtype: int64

In [5]:
import numpy as np
import pandas as pd

In [10]:
df = pd.DataFrame({'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]})

In [11]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [12]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [14]:
df.dropna(axis=1) #Drop nan columns

C
0  1
1  2
2  3

In [15]:
df.dropna(thresh=2) #thresh: require that many non-NA values

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [18]:
df.fillna(value=df.mean()) #fill with mean of that column

A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  1.5  5.0  3

### Group by

In [19]:
import pandas as pd
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [20]:
df = pd.DataFrame(data)

In [21]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [24]:
df.groupby('Company').describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [25]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

### Operations

In [26]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [27]:
df['col2'].unique()

array([444, 555, 666], dtype=int64)

In [28]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [29]:
# Col 1 > 2
# Col2  == 444
#Condition selection
newdf = df[(df['col1']>2) & (df['col2']==444)]

In [30]:
newdf

col1  col2 col3
3     4   444  xyz

In [31]:
def times_two(number):
    return number*2 

In [32]:
times_two(4)

8

In [35]:
#Create a column based on operation of another column
df['new'] = df['col1'].apply(times_two)

In [36]:
df

col1  col2 col3  new
0     1   444  abc    2
1     2   555  def    4
2     3   666  ghi    6
3     4   444  xyz    8

In [37]:
del df['new'] #permanantly remove a column

In [38]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [39]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
col1    4 non-null int64
col2    4 non-null int64
col3    4 non-null object
dtypes: int64(2), object(1)
memory usage: 176.0+ bytes


In [41]:
df.describe()

col1        col2
count  4.000000    4.000000
mean   2.500000  527.250000
std    1.290994  106.274409
min    1.000000  444.000000
25%    1.750000  444.000000
50%    2.500000  499.500000
75%    3.250000  582.750000
max    4.000000  666.000000

In [42]:
#Sort a dataframe
df.sort_values('col2')

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [43]:
df.sort_values('col2',ascending=False)

col1  col2 col3
2     3   666  ghi
1     2   555  def
0     1   444  abc
3     4   444  xyz