In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
arr = np.array(mylist)

In [5]:
arr

array([1, 2, 3])

In [6]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(mylist) #2 dimentional matrix (two square bracket)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
mymatrix = np.array(mylist)

In [10]:
mymatrix.shape

(3, 3)

In [ ]:
mymatrix.

In [14]:
np.arange(0,10,2) #0-10 increment by 2

array([0, 2, 4, 6, 8])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
type(0.) #you will see a lot of time numpy is with zero number

float

In [19]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [21]:
np.ones(4) * 100 #You can do this algerbarically operation with a list. It will return 100 values instead

array([100., 100., 100., 100.])

In [23]:
np.linspace(0,10,3) #give me 3 number that are evenly spaced between 0 - 10

array([ 0.,  5., 10.])

In [28]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [29]:
#Idendity metrax
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
#Create some random array
np.random.rand(5,5) #Random based on uniform distribution

array([[0.15230578, 0.21369442, 0.93172367, 0.34069155, 0.58242256],
       [0.41223363, 0.38007405, 0.54835169, 0.63544598, 0.5361842 ],
       [0.27676359, 0.80111968, 0.3426651 , 0.45216429, 0.5602641 ],
       [0.12609933, 0.20587425, 0.05575624, 0.25359135, 0.79445578],
       [0.67903303, 0.32448285, 0.49903362, 0.82145293, 0.51559268]])

In [35]:
np.random.randn(10) #Based on normal distribution

array([-1.33131068,  0.29787687,  0.07394244, -0.48646182,  0.07829065,
       -0.74752831, -0.89973674, -1.9766144 , -0.35828738, -0.62829618])

In [36]:
#np.random.normal

<function RandomState.normal>

In [40]:
np.random.randint(1,100,200)  #Any 200 random number from 1 - 100

array([46, 64, 20, 38, 32, 85, 92, 61, 81,  3, 77, 77, 86, 19,  1, 65,  3,
       18, 70, 98, 11, 29, 58, 15, 10, 31, 70, 58, 91, 85, 95, 32, 66, 75,
       35, 16, 70, 32,  2, 40, 87, 11, 31, 20, 13, 31,  3, 25, 87,  3, 34,
       48, 45, 45, 34, 38,  4, 80, 38,  6, 75, 80, 37, 93, 35, 13, 63, 29,
       58, 28,  7, 22, 69, 97, 57, 95, 81, 92, 12, 14, 89,  8, 75, 63, 51,
       28, 40, 61, 68, 21, 11, 89, 30, 10, 49, 95,  5, 49, 94, 91, 59, 24,
        3, 91, 77, 91, 10, 88, 81, 41,  7, 81, 85, 84, 69, 57, 82, 55, 91,
       16, 89,  8, 63, 94, 76, 79, 76, 42, 46, 22, 11,  5, 39, 73, 12, 97,
       91, 28, 64, 81, 16, 40,  1,  7, 16, 20, 95, 82, 76, 33, 79, 75, 74,
       33, 79, 44, 93, 43,  7, 88, 91, 71, 85, 89, 49, 26, 85, 67, 90, 77,
       64,  3, 16, 92,  9, 23, 92, 49, 23, 35, 32, 61, 44, 62, 98, 33, 18,
       15, 45, 76, 53, 41, 94,  4, 76, 33, 29, 17, 38, 35])

In [42]:
np.random.seed(42)
np.random.rand(4) #As long as the seed is at the same cell, it will generate the seed results

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [43]:
arr = np.arange(25)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
ranarr = np.random.randint(0,50,10) #random integer

In [47]:
#Reshape array

In [46]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [48]:
ranarr.reshape(5,2)

array([[38, 18],
       [22, 10],
       [10, 23],
       [35, 39],
       [23,  2]])

In [49]:
#Select min max
print(ranarr.max())
print(ranarr.min())

39
2


In [50]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [52]:
ranarr.argmax() #find the index of the max number

7

### NumPy Indexing and Selection

In [53]:
import numpy as np

In [55]:
arr = np.arange(0,11)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr[8]

8

In [59]:
arr[:5]

array([0, 1, 2, 3, 4])

In [60]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [61]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [62]:
arr /2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [63]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

#### Boradcasting on an assignment will affect your original array

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
slice_of_arr = arr[0:6]

In [67]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [68]:
slice_of_arr[:] = 99

In [69]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [70]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [71]:
#You can copy to reassign without changing the original
arr_copy = arr.copy()
arr_copy[:] = 1000

In [72]:
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [73]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [74]:
# Indexing on 2d array
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [84]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
arr_2d.shape

(3, 3)

In [79]:
arr_2d[1]

array([4, 5, 6])

In [80]:
arr_2d[1][1]

5

In [81]:
arr_2d[1,1]

5

In [82]:
arr_2d[2,2]

9

In [85]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [86]:
arr = np.arange(1,11)

In [87]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [89]:
bool_arr = arr>4

In [91]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [93]:
arr[bool_arr] #pass the boolean array to the original to select elements

array([ 5,  6,  7,  8,  9, 10])

In [94]:
#One step
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [95]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [96]:
 np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [98]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
arr_2d.sum(axis = 0) #Sum across the rows

array([12, 15, 18])

In [100]:
arr_2d.sum(axis = 1) #Sum across the column

array([ 6, 15, 24])